[package]
name = "opengl_monstrosity"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "0.30"
nalgebra-glm = "0.15"
tokio = "1.14"
image = "0.23"
arrayvec = "0.7.2"